### ISSUE TITLE
[bug] file option doesn't work

### ISSUE THREAD

**Issue by manasesjesus** [philips-software/post-to-medium-action#26]
I've tried the `file` option in different ways, but it just doesn't work. Can you provide a working snippet? 

In the workflow as:
```yml
        uses: philips-software/post-to-medium-action@v0.4.1
        with:
          file: "./README.md"
```

No matter how I specify the file path, it always returns the same error.
```ssh
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/github/workspace/README.md'.
File name: '/github/workspace/README.md'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions
```

**Comment by manasesjesus** [comment]
I solved it by adding the checkout step before. It'd be nice to specify this on your action's readme.

```yml
steps:
  - name: Checking out reposity
    uses: actions/checkout@v2
  - name: Publishing to Medium
    uses: philips-software/post-to-medium-action@v0.4.1
```

**Comment by Brend-Smits** [comment]
Thank you for creating this issue and suggesting an improvement to the readme. Happy to accept a PR if you have time to contribute.
If you don’t, no problem, I will try to improve the docs as soon as possible! 

Thank you for your time 🙏
